version: '3.8'
services:
  frontend:
    build:
      context: ../TaskPlannerFrontendService
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ../TaskPlannerApiGateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend


  backend:
    build:
      context: ../TaskPlannerBackendService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_URL=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}


  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=taskPlanner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d taskPlanner"]
      interval: 5s
      retries: 5


volumes:
  postgres_data:
